import SignedOutNavigation from "@/components/SignedOutNavigation"
import customTheme from "@/config/chakraTheme"
import { Box, ChakraProvider } from "@chakra-ui/react"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  console.log('customTheme', customTheme)
  console.log("main layout")
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <SignedOutNavigation />
          <Box maxW={"1440px"} mx={"auto"}>
            {children}
          </Box>
          <footer></footer>
        </ChakraProvider>
      </body>
    </html>
  )
}
